### --- Builder --- ###
FROM golang:1.22 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o replog ./cmd/replog/main.go

### --- Binary --- ###
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /app/replog .

USER nonroot:nonroot

ENTRYPOINT ["/replog"]
