CREATE TABLE "replog_entry" (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) REFERENCES "user"(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
);

CREATE TABLE "replog_line" (
  id VARCHAR(255) PRIMARY KEY,
  entry_id VARCHAR(255) REFERENCES "entry"(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
);
