CREATE TABLE "user" (
  id VARCHAR(255) PRIMARY KEY
  name VARCHAR(255) NOT NULL
  discord_id VARCHAR(255)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
